# Usa Java 17
FROM openjdk:17-jdk-slim

# Carpeta de trabajo
WORKDIR /app

# Copiar todo
COPY . .

# Dar permisos a mvnw
RUN chmod +x mvnw

# Build
RUN ./mvnw clean package -DskipTests

# Exponer puerto
EXPOSE 8080

# Ejecutar app
CMD ["java", "-jar", "target/*.jar"]