spring.application.name=Nutrition
server.address=0.0.0.0

#PORT dinámico (Render)
server.port=${PORT:8080}

#DATABASE dinámica
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/nutrition_app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true