spring.application.name=Nutrition
server.address=0.0.0.0
server.port=${PORT:8080}

# ===============================
# DATASOURCE (LOCAL + RENDER)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/nutrition_app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Detecta dialecto
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:}

# ===============================
# DRIVER (AUTO PERO LO FORZAMOS)
# ===============================
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}